name: Deploy Dist
on: [push,workflow_dispatch]
#on:
#    - push
#    - workflow_dispach

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Get Clone"
        run: |
          echo "Clonnig Git repo..."
          echo "${{toJson(github)}}"
          git clone https://github.com/${{github.repository}}.git